version: "3.7"
services:
        redis:
                container_name: "qiusuo-redis"
                image: "redis:5.0"
                networks:
                        - qiusuo-cluster
                ports:
                        - "6479:6379"