/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "springboottutorial"
include("springbootcassandra")
include("springbootredis")
include("springbootrabbitmq")
include("springbootwebsocket")
include("springbootmessaging")
include("springdroolstutorial")
include("RMITutorial")
include("sprinbwebfluxtutorial")

