/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "springboottutorial"
include("springbootcassandra")
include("springbootredis")
include("springbootrabbitmq")
include("springbootwebsocket")
include("springbootmessaging")
include("springdroolstutorial")
include("RMITutorial")
include("springwebfluxtutorial")
include("springkafkatutorial")
include("springcoretutorial")
include("springjpatutorial")
include("springkafkatutorial:warehouseservice")
include("springkafkatutorial:accountingservice")
include("springkafkatutorial:deliveryservice")
include("springkafkatutorial:orderservice")
include("springkafkatutorial:csvproducer")
include("qsol-data-r2dbc-spring")
include("qsol-coding-guideline")
include("qsol-data-reactive-spring-boot-starter")
include("qsol-data-reactive-spring-boot-autoconfigure")
