server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/{application}

kafka:
  bootstrap:
    servers: localhost:9092
