/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation("org.kie:kie-api:6.2.0.Final")
    implementation("org.drools:drools-core:6.2.0.Final")
    implementation("org.drools:drools-compiler:6.2.0.Final")
    implementation("org.kie:kie-ci:6.2.0.Final")
}
