version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ../data/vol1/zk-data:/var/lib/zookeeper/data
      - ../data/vol2/zk-txn-logs:/var/lib/zookeeper/log
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/vol3/kafka-data:/var/lib/kafka/data

networks:

