/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.qiusuo.common")
}
dependencies {
    implementation("org.springframework.data:spring-data-redis")
    implementation("redis.clients:jedis")
}
