version: "3.7"
services:
  rocketmq-stomp:
    build: .
    image: rocketmq-stomp:v1
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

networks:
  default:
    external:
      name: dev_qiusuo-cluster
