version: "3.7"
services:
  redis:
    container_name: 'qiusuo-redis-chat'
    image: 'redis:latest'
    ports:
      - "6379:6379"

  rocketmq-stomp:
    build: .
    image: rocketmq-stomp:v1
    container_name: rabbitmq-chat
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"

networks:
  default:
    external:
      name: dev-qiusuo-cluster
