CREATE TABLE book (iso_number VARCHAR(255) PRIMARY KEY, title VARCHAR(255));
CREATE TABLE qiusuousers (id VARCHAR(50) PRIMARY KEY, name VARCHAR(50));
CREATE TABLE user2book (user_id VARCHAR(50) NOT NULL,
     book_id VARCHAR(50) NOT NULL,
     FOREIGN KEY (user_id) REFERENCES qiusuousers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
     FOREIGN KEY (book_id) REFERENCES book (iso_number) ON DELETE RESTRICT ON UPDATE CASCADE,
     PRIMARY KEY (user_id, book_id));